import pathlib
p = pathlib.Path(r'D:\作业\实训二\tlias\tlias-web\src\views\dept\DeptList.vue')
lines = []
lines.append('<template>')
lines.append('<div class="page-container">')
lines.append('<div class="page-header">')
lines.append('<h2>\u90e8\u95e8\u7ba1\u7406</h2>')
lines.append('<el-button type="primary" @click="openDialog(null)">+ \u65b0\u589e\u90e8\u95e8</el-button>')
lines.append('</div>')
lines.append('<el-card shadow="never">')
lines.append('<el-table :data="deptList" stripe v-loading="loading">')
lines.append('<el-table-column type="index" label="\u5e8f\u53f7" width="80" />')
lines.append('<el-table-column prop="name" label="\u90e8\u95e8\u540d\u79f0" min-width="180" />')
lines.append('<el-table-column prop="updateTime" label="\u6700\u540e\u64cd\u4f5c\u65f6\u95f4" min-width="200" />')
lines.append('<el-table-column label="\u64cd\u4f5c" width="160" fixed="right">')
lines.append('<template #default="{ row }">')
lines.append('<el-button type="primary" link size="small" @click="openDialog(row)">\u7f16\u8f91</el-button>')
lines.append('<el-button type="danger" link size="small" @click="handleDelete(row.id)">\u5220\u9664</el-button>')
lines.append('</template>')
lines.append('</el-table-column>')
lines.append('</el-table>')
lines.append('</el-card>')
lines.append('<el-dialog v-model="dialogVisible" :title="isEdit ? \'\u7f16\u8f91\u90e8\u95e8\' : \'\u65b0\u589e\u90e8\u95e8\'" width="420px">')
lines.append('<el-form ref="formRef" :model="form" :rules="rules" label-width="80px">')
lines.append('<el-form-item label="\u90e8\u95e8\u540d\u79f0" prop="name">')
lines.append('<el-input v-model="form.name" placeholder="\u8bf7\u8f93\u5165\u90e8\u95e8\u540d\u79f0" maxlength="10" />')
lines.append('</el-form-item>')
lines.append('</el-form>')
lines.append('<template #footer>')
lines.append('<el-button @click="dialogVisible = false">\u53d6\u6d88</el-button>')
lines.append('<el-button type="primary" :loading="saving" @click="handleSave">\u786e\u8ba4</el-button>')
lines.append('</template>')
lines.append('</el-dialog>')
lines.append('</div>')
lines.append('</template>')
p.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('Template OK')
